### ISSUE TITLE
When I copied this password it was 1 char longer than expected

### ISSUE THREAD

**Issue by PreetSangha** [bitesized/password-generator#6]
<img width="315" alt="image" src="https://user-images.githubusercontent.com/15098094/209884035-3f95eb95-9fe6-4dc8-9e79-a931405680f1.png">

**Comment by bitesized** [comment]
count the characters my man

**Comment by PreetSangha** [comment]
The copy had an extra space at the end.

regards,
Preet, in Auckland NZ
